### ISSUE TITLE
UnboundLocalError: local variable 'res' referenced before assignment

### ISSUE THREAD

**Issue by jameswangcnbj** [ouyanghuiyu/chineseocr_lite#110]
部分图片识别时报错：
Traceback (most recent call last):
  File "/usr/local/anaconda3/envs/torch-ocr/lib/python3.7/site-packages/web/application.py", line 290, in process
    return self.handle()
  File "/usr/local/anaconda3/envs/torch-ocr/lib/python3.7/site-packages/web/application.py", line 281, in handle
    return self._delegate(fn, self.fvars, args)
  File "/usr/local/anaconda3/envs/torch-ocr/lib/python3.7/site-packages/web/application.py", line 531, in _delegate
    return handle_class(cls)
  File "/usr/local/anaconda3/envs/torch-ocr/lib/python3.7/site-packages/web/application.py", line 509, in handle_class
    return tocall(*args)
  File "/root/chineseocr_lite/app.py", line 118, in POST
    return json.dumps({'res':res,'timeTake':round(timeTake,4)},ensure_ascii=False)
UnboundLocalError: local variable 'res' referenced before assignment

还有的：
Traceback (most recent call last):
  File "/usr/local/anaconda3/envs/torch-ocr/lib/python3.7/site-packages/web/application.py", line 288, in process
    return p(lambda: process(processors))
  File "/usr/local/anaconda3/envs/torch-ocr/lib/python3.7/site-packages/web/application.py", line 700, in processor
    return handler()
  File "/usr/local/anaconda3/envs/torch-ocr/lib/python3.7/site-packages/web/application.py", line 288, in <lambda>
    return p(lambda: process(processors))
  File "/usr/local/anaconda3/envs/torch-ocr/lib/python3.7/site-packages/web/application.py", line 297, in process
    raise self.internalerror()
  File "/usr/local/anaconda3/envs/torch-ocr/lib/python3.7/site-packages/web/application.py", line 588, in internalerror
    return debugerror()
  File "/usr/local/anaconda3/envs/torch-ocr/lib/python3.7/site-packages/web/debugerror.py", line 337, in debugerror
    return web._InternalError(djangoerror())
  File "/usr/local/anaconda3/envs/torch-ocr/lib/python3.7/site-packages/web/debugerror.py", line 315, in djangoerror
    djangoerror_r = Template(djangoerror_t, filename=__file__, filter=websafe)
  File "/usr/local/anaconda3/envs/torch-ocr/lib/python3.7/site-packages/web/template.py", line 943, in __init__
    code = self.compile_template(text, filename)
  File "/usr/local/anaconda3/envs/torch-ocr/lib/python3.7/site-packages/web/template.py", line 1020, in compile_template
    compiled_code = compile(code, filename, "exec")
  File "/usr/local/anaconda3/envs/torch-ocr/lib/python3.7/site-packages/web/debugerror.py", line 8
    def with (exception_type, exception_value, frames)
           ^
SyntaxError: invalid syntax

Template traceback:
    File '/usr/local/anaconda3/envs/torch-ocr/lib/python3.7/site-packages/web/debugerror.py', line 8
        http://www.xfree86.org/3.3.6/COPYRIGHT2.html#5

**Comment by ChenZhaobin** [comment]
请问解决了吗
