### ISSUE TITLE
RuntimeError: CUDA error: all CUDA-capable devices are busy or unavailable

### ISSUE THREAD

**Issue by jameswangcnbj** [ouyanghuiyu/chineseocr_lite#111]
Traceback (most recent call last):
  File "app.py", line 12, in <module>
    from model import  text_predict,crnn_handle
  File "/opt/chineseocr_lite/model.py", line 16, in <module>
    text_handle = PSENetHandel(pse_model_path, text_detect_net, pse_scale, gpu_id=GPU_ID)
  File "/opt/chineseocr_lite/psenet/PSENET.py", line 25, in __init__
    self.net = torch.load(model_path, map_location=self.device)['state_dict']
  File "/root/anaconda3/envs/torch-ocr/lib/python3.7/site-packages/torch/serialization.py", line 386, in load
    return _load(f, map_location, pickle_module, **pickle_load_args)
  File "/root/anaconda3/envs/torch-ocr/lib/python3.7/site-packages/torch/serialization.py", line 573, in _load
    result = unpickler.load()
  File "/root/anaconda3/envs/torch-ocr/lib/python3.7/site-packages/torch/serialization.py", line 536, in persistent_load
    deserialized_objects[root_key] = restore_location(obj, location)
  File "/root/anaconda3/envs/torch-ocr/lib/python3.7/site-packages/torch/serialization.py", line 406, in restore_location
    return default_restore_location(storage, str(map_location))
  File "/root/anaconda3/envs/torch-ocr/lib/python3.7/site-packages/torch/serialization.py", line 119, in default_restore_location
    result = fn(storage, location)
  File "/root/anaconda3/envs/torch-ocr/lib/python3.7/site-packages/torch/serialization.py", line 99, in _cuda_deserialize
    return storage_type(obj.size())
  File "/root/anaconda3/envs/torch-ocr/lib/python3.7/site-packages/torch/cuda/__init__.py", line 615, in _lazy_new
    return super(_CudaBase, cls).__new__(cls, *args, **kwargs)
RuntimeError: CUDA error: all CUDA-capable devices are busy or unavailable

config.py中的gpu_id=0 需要调整或者更换其他配置吗？

**Comment by jameswangcnbj** [comment]
我的torch.cuda.is_available()的值为true

**Comment by jameswangcnbj** [comment]
代码中的psenet是否只配置在cpu环境下的编译，如何调整整个项目为gpu模式下呢？@ouyanghuiyu

**Comment by jameswangcnbj** [comment]
最终发现是阿里云环境问题，解决完CUDA后就正常了

**Comment by Ffmydy** [comment]
@jameswangcnbj 我也用的是阿里云，遇到同样的问题，请问是什么样子的环境问题

**Comment by yuanzhuohao** [comment]
@jameswangcnbj 我也是遇到这情况，怎么解决的？
