### ISSUE TITLE
AttributeError: 'StaticApp' object has no attribute 'directory'

### ISSUE THREAD

**Issue by li829** [ouyanghuiyu/chineseocr_lite#144]
对web的utils这样修改后：
            try:
                yield next(seq)
            except StopIteration:
                return
出现下面的错误：
Traceback (most recent call last):
  File "/home/liyuewen/anaconda3/envs/pytorch/lib/python3.7/site-packages/web/wsgiserver/wsgiserver3.py", line 1089, in communicate
    req.respond()
  File "/home/liyuewen/anaconda3/envs/pytorch/lib/python3.7/site-packages/web/wsgiserver/wsgiserver3.py", line 877, in respond
    self.server.gateway(self).respond()
  File "/home/liyuewen/anaconda3/envs/pytorch/lib/python3.7/site-packages/web/wsgiserver/wsgiserver3.py", line 1982, in respond
    for chunk in response:
  File "/home/liyuewen/anaconda3/envs/pytorch/lib/python3.7/site-packages/web/httpserver.py", line 255, in __iter__
    path = self.translate_path(self.path)
  File "/home/liyuewen/anaconda3/envs/pytorch/lib/python3.7/http/server.py", line 820, in translate_path
    path = self.directory
AttributeError: 'StaticApp' object has no attribute 'directory'

**Comment by li829** [comment]
换成python3.6就行了
