### ISSUE TITLE
执行python app.py出现错误

### ISSUE THREAD

**Issue by pzibang** [ouyanghuiyu/chineseocr_lite#202]
Traceback (most recent call last):
  File "app.py", line 12, in <module>
    from model import text_predict, crnn_handle
  File "pse\chineseocr_lite\model.py", line 10, in <module>
    from dbnet.dbnet_infer import DBNET
ModuleNotFoundError: No module named 'dbnet.dbnet_infer'
其他的依赖都通过错误安装上了，最后还剩下这两个，找不到解决方法，源码中也没有对应的包

**Comment by huye** [comment]
我这里是访问 http://xxxx/ocr 报错
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe5 in position 972: ordinal not in range(128)

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/web/application.py", line 257, in process
    return self.handle()
  File "/usr/local/lib/python3.6/site-packages/web/application.py", line 248, in handle
    return self._delegate(fn, self.fvars, args)
  File "/usr/local/lib/python3.6/site-packages/web/application.py", line 488, in _delegate
    return handle_class(cls)
  File "/usr/local/lib/python3.6/site-packages/web/application.py", line 466, in handle_class
    return tocall(*args)
  File "/data/chineseocr_lite/app.py", line 43, in GET
    return render.ocr(post)
  File "/usr/local/lib/python3.6/site-packages/web/template.py", line 1034, in __getattr__
    t = self._template(name)
  File "/usr/local/lib/python3.6/site-packages/web/template.py", line 1031, in _template
    return self._load_template(name)
  File "/usr/local/lib/python3.6/site-packages/web/template.py", line 1016, in _load_template
    return Template(open(path).read(), filename=path, **self._keywords)
  File "/usr/lib64/python3.6/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]

**Comment by zouxiaoshi** [comment]
同报错：

Traceback (most recent call last):
  File "/Users/yuankaizou/.conda/envs/pytorch/lib/python3.7/site-packages/web/utils.py", line 526, in take
    yield next(seq)
StopIteration

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/yuankaizou/Documents/Codes/chineseocr_lite/app.py", line 118, in <module>
    app = web.application(urls, globals())
  File "/Users/yuankaizou/.conda/envs/pytorch/lib/python3.7/site-packages/web/application.py", line 62, in __init__
    self.init_mapping(mapping)
  File "/Users/yuankaizou/.conda/envs/pytorch/lib/python3.7/site-packages/web/application.py", line 130, in init_mapping
    self.mapping = list(utils.group(mapping, 2))
  File "/Users/yuankaizou/.conda/envs/pytorch/lib/python3.7/site-packages/web/utils.py", line 531, in group
    x = list(take(seq, size))
RuntimeError: generator raised StopIteration

Process finished with exit code 1

**Comment by shijie2951** [comment]
有人成功解决吗
from dbnet.dbnet_infer import DBNET
ModuleNotFoundError: No module named 'dbnet.dbnet_infer'
明明有dbnet.dbnet_infer这个文件，文件中也有DBNET这个方法  为什么运行就报错
