### ISSUE TITLE
500 Internal Server Error

### ISSUE THREAD

**Issue by Amither111** [ouyanghuiyu/chineseocr_lite#21]
运行python app.py 8080后终端显示：
make: Entering directory '/home/amither/Downloads/chineseocr_lite-master/psenet/pse'
make: 'pse.so' is up to date.
make: Leaving directory '/home/amither/Downloads/chineseocr_lite-master/psenet/pse'
device: cpu
load models
device: cpu
load models
device: cpu
load models
device: cpu
load model
http://0.0.0.0:8080/
127.0.0.1:58938 - - [10/Mar/2020 16:34:06] "HTTP/1.1 GET /ocr" - 200 OK

然后当我选择了一张图片后，就会一直打转不出结果，终端显示如下：
127.0.0.1:58938 - - [10/Mar/2020 16:34:06] "HTTP/1.1 GET /favicon.ico" - 404 Not Found
Traceback (most recent call last):
  File "/home/amither/tensorflow/lib/python3.5/site-packages/web/application.py", line 257, in process
    return self.handle()
  File "/home/amither/tensorflow/lib/python3.5/site-packages/web/application.py", line 248, in handle
    return self._delegate(fn, self.fvars, args)
  File "/home/amither/tensorflow/lib/python3.5/site-packages/web/application.py", line 488, in _delegate
    return handle_class(cls)
  File "/home/amither/tensorflow/lib/python3.5/site-packages/web/application.py", line 466, in handle_class
    return tocall(*args)
  File "/home/amither/Downloads/chineseocr_lite-master/app.py", line 51, in POST
    data = json.loads(data)
  File "/usr/lib/python3.5/json/__init__.py", line 312, in loads
    s.__class__.__name__))
TypeError: the JSON object must be str, not 'bytes'

127.0.0.1:58938 - - [10/Mar/2020 16:34:12] "HTTP/1.1 POST /ocr" - 500 Internal Server Error

Platform: VMware Ubuntu 16.04 python3.5.2 Pytorch1.4.0+cpu
请问这是为什么？

**Comment by ouyanghuiyu** [comment]
web.py 没安装对？

**Comment by Amither111** [comment]
> web.py 没安装对？
pip install web.py==0.40.dev0
Requirement already satisfied: web.py==0.40.dev0 in /home/amither/tensorflow/lib/python3.5/site-packages (0.40.dev0)
这个不对吗？

**Comment by wozwdaqian** [comment]
可以参考这个https://blog.csdn.net/weixin_38648232/article/details/88687668

**Comment by Amither111** [comment]
> 可以参考这个https://blog.csdn.net/weixin_38648232/article/details/88687668

改了后就可以了，感谢^_^
