### ISSUE TITLE
test error

### ISSUE THREAD

**Issue by zhaojc001** [ouyanghuiyu/chineseocr_lite#227]
when I test the project,it appears the following error,please help me:
HTTPServerRequest(protocol='http', host='192.168.50.13:8089', method='POST', uri
sion='HTTP/1.1', remote_ip='192.168.50.13')
Traceback (most recent call last):
  File "E:\Python36\lib\site-packages\tornado\web.py", line 1592, in _execute
    result = yield result
  File "E:\Python36\lib\site-packages\tornado\gen.py", line 1133, in run
    value = future.result()
  File "E:\Python36\lib\site-packages\tornado\gen.py", line 307, in wrapper
    result = func(*args, **kwargs)
  File "E:\Python36\lib\types.py", line 248, in wrapped
    coro = func(*args, **kwargs)
  File "E:\space\ocr\chineseocr_lite\backend\webInterface\tr_run.py", line 109,
    res = ocrhandle.text_predict(img)
  File "E:\space\ocr\chineseocr_lite\model.py", line 54, in text_predict
    boxes_list, score_list = self.text_handle.process(np.asarray(img).astype(np.
  File "E:\space\ocr\chineseocr_lite\dbnet\dbnet_infer.py", line 79, in process
    box_list, score_list = self.decode_handel(out[0][0], h, w)
  File "E:\space\ocr\chineseocr_lite\dbnet\decode.py", line 33, in __call__
    boxes, scores = self.boxes_from_bitmap(pred, segmentation, width, height)
  File "E:\space\ocr\chineseocr_lite\dbnet\decode.py", line 52, in boxes_from_bi
    contours, _ = cv2.findContours((bitmap * 255).astype(np.uint8), cv2.RETR_LIS
SIMPLE)
ValueError: too many values to unpack (expected 2)
ERROR:tornado.access:500 POST /api/tr-run/ (192.168.50.13) 1232.87ms

**Comment by zhaojc001** [comment]
I know the error,the code is unsupported the windows os.

**Comment by caozhongbjtu** [comment]
I got the same error,can't the code run on windows?    but author says it can

**Comment by ouyanghuiyu** [comment]
opencv version

**Comment by caozhongbjtu** [comment]
我实在windows用的，opencv版本和你的一样，但还是报错了。。。
