### ISSUE TITLE
ModuleNotFoundError: No module named 'crnn.CRNN'

### ISSUE THREAD

**Issue by sevenseablue** [ouyanghuiyu/chineseocr_lite#23]
Traceback (most recent call last):
  File "app.py", line 12, in <module>
    from model import  text_predict,crnn_handle
  File "/home/wangdawei/github/ocr/chineseocr_lite/model.py", line 1, in <module>
    from config import  *
  File "/home/wangdawei/github/ocr/chineseocr_lite/config.py", line 40, in <module>
    from crnn.keys import  alphabetChinese as alphabet
  File "/home/wangdawei/github/ocr/chineseocr_lite/crnn/__init__.py", line 3, in <module>
    from .CRNN import CRNNHandle
ModuleNotFoundError: No module named 'crnn.CRNN'

**Comment by ouyanghuiyu** [comment]
你好 不好意思 今天push的时候吧CRNN误删了，现在传了，你复制一下，在crnn目录下面的CRNN.py
