### ISSUE TITLE
another test error

### ISSUE THREAD

**Issue by caozhongbjtu** [ouyanghuiyu/chineseocr_lite#230]
Traceback (most recent call last):
  File "D:\Anaconda\lib\site-packages\tornado\web.py", line 1592, in _execute
    result = yield result
  File "D:\Anaconda\lib\site-packages\tornado\gen.py", line 1133, in run
    value = future.result()
  File "D:\Anaconda\lib\site-packages\tornado\gen.py", line 307, in wrapper
    result = func(*args, **kwargs)
  File "D:\Anaconda\lib\types.py", line 248, in wrapped
    coro = func(*args, **kwargs)
  File "E:\chineseocr_lite-onnx\backend\webInterface\tr_run.py", line 109, in post
    res = ocrhandle.text_predict(img)
  File "E:\chineseocr_lite-onnx\model.py", line 54, in text_predict
    boxes_list, score_list = self.text_handle.process(np.asarray(img).astype(np.uint8))
  File "E:\chineseocr_lite-onnx\dbnet\dbnet_infer.py", line 79, in process
    box_list, score_list = self.decode_handel(out[0][0], h, w)
  File "E:\chineseocr_lite-onnx\dbnet\decode.py", line 33, in __call__
    boxes, scores = self.boxes_from_bitmap(pred, segmentation, width, height)
  File "E:\chineseocr_lite-onnx\dbnet\decode.py", line 58, in boxes_from_bitmap
    contour = contours[index].squeeze(1)
ValueError: cannot select an axis to squeeze out which has size not equal to one
ERROR:tornado.access:500 POST /api/tr-run/ (172.16.9.173) 2063.81ms

anyone can tell me why?

**Comment by ouyanghuiyu** [comment]
pip install -r requirements.txt  and try again?

**Comment by caozhongbjtu** [comment]
> pip install -r requirements.txt and try again?

ok,it can works,thanks
