### ISSUE TITLE
python3.6运行，报错，上传图片时就报错。

### ISSUE THREAD

**Issue by xinsuinizhuan** [ouyanghuiyu/chineseocr_lite#238]
![图片](https://user-images.githubusercontent.com/40679769/90334887-5b545a80-e003-11ea-8ea8-75ff961e9ff3.png)
server is running: 192.168.1.3:8089
ERROR:tornado.application:Uncaught exception POST /api/tr-run/ (192.168.1.3)
HTTPServerRequest(protocol='http', host='192.168.1.3:8089', method='POST', uri='/api/tr-run/', version='HTTP/1.1', remote_ip='192.168.1.3')
Traceback (most recent call last):
  File "E:\Anaconda_software\envs\nilmtk-env\lib\site-packages\tornado\web.py", line 1592, in _execute
    result = yield result
  File "E:\Anaconda_software\envs\nilmtk-env\lib\site-packages\tornado\gen.py", line 1133, in run
    value = future.result()
  File "E:\Anaconda_software\envs\nilmtk-env\lib\site-packages\tornado\gen.py", line 307, in wrapper
    result = func(*args, **kwargs)
  File "E:\Anaconda_software\envs\nilmtk-env\lib\types.py", line 248, in wrapped
    coro = func(*args, **kwargs)
  File "F:\my_item\chineseocr_lite-onnx\backend\webInterface\tr_run.py", line 93, in post
    img.save("../web_imgs/{}.jpg".format(time_now))
  File "E:\Anaconda_software\envs\nilmtk-env\lib\site-packages\PIL\Image.py", line 2155, in save
    fp = builtins.open(filename, "w+b")
FileNotFoundError: [Errno 2] No such file or directory: '../web_imgs/2020-08-16-20_54_52.jpg'
ERROR:tornado.access:500 POST /api/tr-run/ (192.168.1.3) 856.51ms
ERROR:tornado.application:Uncaught exception POST /api/tr-run/ (192.168.1.3)
HTTPServerRequest(protocol='http', host='192.168.1.3:8089', method='POST', uri='/api/tr-run/', version='HTTP/1.1', remote_ip='192.168.1.3')
Traceback (most recent call last):
  File "E:\Anaconda_software\envs\nilmtk-env\lib\site-packages\tornado\web.py", line 1592, in _execute
    result = yield result
  File "E:\Anaconda_software\envs\nilmtk-env\lib\site-packages\tornado\gen.py", line 1133, in run
    value = future.result()
  File "E:\Anaconda_software\envs\nilmtk-env\lib\site-packages\tornado\gen.py", line 307, in wrapper
    result = func(*args, **kwargs)
  File "E:\Anaconda_software\envs\nilmtk-env\lib\types.py", line 248, in wrapped
    coro = func(*args, **kwargs)
  File "F:\my_item\chineseocr_lite-onnx\backend\webInterface\tr_run.py", line 93, in post
    img.save("../web_imgs/{}.jpg".format(time_now))
  File "E:\Anaconda_software\envs\nilmtk-env\lib\site-packages\PIL\Image.py", line 2155, in save
    fp = builtins.open(filename, "w+b")
FileNotFoundError: [Errno 2] No such file or directory: '../web_imgs/2020-08-16-20_58_37.jpg'
ERROR:tornado.access:500 POST /api/tr-run/ (192.168.1.3) 68.96ms

**Comment by QQ1696311291** [comment]
我也遇到这个问题了，请问你解决了吗？

**Comment by xinsuinizhuan** [comment]
> 
> 
> 我也遇到这个问题了，请问你解决了吗？

在当前目录下新建一个web_imgs目录即可。

**Comment by siyuzhong94** [comment]
> ![图片](https://user-images.githubusercontent.com/40679769/90334887-5b545a80-e003-11ea-8ea8-75ff961e9ff3.png)
> server is running: 192.168.1.3:8089
> ERROR:tornado.application:Uncaught exception POST /api/tr-run/ (192.168.1.3)
> HTTPServerRequest(protocol='http', host='192.168.1.3:8089', method='POST', uri='/api/tr-run/', version='HTTP/1.1', remote_ip='192.168.1.3')
> Traceback (most recent call last):
> File "E:\Anaconda_software\envs\nilmtk-env\lib\site-packages\tornado\web.py", line 1592, in _execute
> result = yield result
> File "E:\Anaconda_software\envs\nilmtk-env\lib\site-packages\tornado\gen.py", line 1133, in run
> value = future.result()
> File "E:\Anaconda_software\envs\nilmtk-env\lib\site-packages\tornado\gen.py", line 307, in wrapper
> result = func(*args, **kwargs)
> File "E:\Anaconda_software\envs\nilmtk-env\lib\types.py", line 248, in wrapped
> coro = func(*args, **kwargs)
> File "F:\my_item\chineseocr_lite-onnx\backend\webInterface\tr_run.py", line 93, in post
> img.save("../web_imgs/{}.jpg".format(time_now))
> File "E:\Anaconda_software\envs\nilmtk-env\lib\site-packages\PIL\Image.py", line 2155, in save
> fp = builtins.open(filename, "w+b")
> FileNotFoundError: [Errno 2] No such file or directory: '../web_imgs/2020-08-16-20_54_52.jpg'
> ERROR:tornado.access:500 POST /api/tr-run/ (192.168.1.3) 856.51ms
> ERROR:tornado.application:Uncaught exception POST /api/tr-run/ (192.168.1.3)
> HTTPServerRequest(protocol='http', host='192.168.1.3:8089', method='POST', uri='/api/tr-run/', version='HTTP/1.1', remote_ip='192.168.1.3')
> Traceback (most recent call last):
> File "E:\Anaconda_software\envs\nilmtk-env\lib\site-packages\tornado\web.py", line 1592, in _execute
> result = yield result
> File "E:\Anaconda_software\envs\nilmtk-env\lib\site-packages\tornado\gen.py", line 1133, in run
> value = future.result()
> File "E:\Anaconda_software\envs\nilmtk-env\lib\site-packages\tornado\gen.py", line 307, in wrapper
> result = func(*args, **kwargs)
> File "E:\Anaconda_software\envs\nilmtk-env\lib\types.py", line 248, in wrapped
> coro = func(*args, **kwargs)
> File "F:\my_item\chineseocr_lite-onnx\backend\webInterface\tr_run.py", line 93, in post
> img.save("../web_imgs/{}.jpg".format(time_now))
> File "E:\Anaconda_software\envs\nilmtk-env\lib\site-packages\PIL\Image.py", line 2155, in save
> fp = builtins.open(filename, "w+b")
> FileNotFoundError: [Errno 2] No such file or directory: '../web_imgs/2020-08-16-20_58_37.jpg'
> ERROR:tornado.access:500 POST /api/tr-run/ (192.168.1.3) 68.96ms

老哥，解决了么，我这边也遇到了问题，没法解决，如果解决了方便告知一下咋做的么
