### ISSUE TITLE
弄个qq群吧  使用的问题太多 不适合这里提

### ISSUE THREAD

**Issue by Matiz7** [ouyanghuiyu/chineseocr_lite#241]
model.py修改为
```
if __name__ == "__main__":
    ocr = OcrHandle()
    img = cv2.imread( sys.argv[1] )
    result = ocr.text_predict(img, 16)
    print(result)
```
执行 python model.py ../img/1588984862473.jpg 报错 
2020-08-19 14:45:50.602008656 [E:onnxruntime:, sequential_executor.cc:281 Execute] Non-zero status code returned while running Add node. Name:'' Status Message: /onnxruntime_src/onnxruntime/core/providers/cpu/math/element_wise_ops.h:351 void onnxruntime::BroadcastIterator::Init(int64_t, int64_t) axis == 1 || axis == largest was false. Attempting to broadcast an axis by a dimension other than 1. 2 by 4

Traceback (most recent call last):
  File "model.py", line 88, in <module>
    result = ocr.text_predict(img, 16)
  File "model.py", line 78, in text_predict
    boxes_list, score_list = self.text_handle.process(np.asarray(img).astype(np.uint8),short_size=short_size)
  File "/home/admin/wangyongjun/torch/chineseocr_lite-onnx/dbnet/dbnet_infer.py", line 79, in process
    out = self.sess.run(["out1"], {"input0": transformed_image.astype(np.float32)})
  File "/usr/local/lib64/python3.6/site-packages/onnxruntime/capi/session.py", line 111, in run
    return self._sess.run(output_names, input_feed, run_options)
onnxruntime.capi.onnxruntime_pybind11_state.RuntimeException: [ONNXRuntimeError] : 6 : RUNTIME_EXCEPTION : Non-zero status code returned while running Add node. Name:'' Status Message: /onnxruntime_src/onnxruntime/core/providers/cpu/math/element_wise_ops.h:351 void onnxruntime::BroadcastIterator::Init(int64_t, int64_t) axis == 1 || axis == largest was false. Attempting to broadcast an axis by a dimension other than 1. 2 by 4
该怎么改

**Comment by Matiz7** [comment]
150387328 群号码是这，申请备注ocr 即可

**Comment by xinsuinizhuan** [comment]
同建议，弄个QQ群或者微信群，方便交流！

**Comment by Matiz7** [comment]
> 同建议，弄个QQ群或者微信群，方便交流！

1080729300   往前翻了翻，已经有这个群了，加这个吧

**Comment by Matiz7** [comment]
result = ocr.text_predict(img, 16)      16改成960运行正常了

**Comment by xinsuinizhuan** [comment]
> 1080729300

这个群，不太纯正，yolo和ocr的，里面讨论啥的都有，建议专门弄一个讨论这个项目的。

**Comment by ouyanghuiyu** [comment]
@xinsuinizhuan 那我来建一个吧

**Comment by ouyanghuiyu** [comment]
994929053 群已创建哦
