### ISSUE TITLE
app.py中的变量定义有问题？local variable 'res' referenced before assignment

### ISSUE THREAD

**Issue by Caesarthegreat** [ouyanghuiyu/chineseocr_lite#34]
192.168.11.99:53801 - - [12/Mar/2020 17:36:51] "HTTP/1.1 POST /ocr" - 500 Internal Server Error
192.168.11.99:53995 - - [12/Mar/2020 17:40:27] "HTTP/1.1 GET /ocr" - 200 OK
192.168.11.99:54217 - - [12/Mar/2020 17:43:11] "HTTP/1.1 GET /ocr" - 200 OK
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.8/site-packages/web/application.py", line 257, in process
    return self.handle()
  File "/usr/local/python3/lib/python3.8/site-packages/web/application.py", line 248, in handle
    return self._delegate(fn, self.fvars, args)
  File "/usr/local/python3/lib/python3.8/site-packages/web/application.py", line 488, in _delegate
    return handle_class(cls)
  File "/usr/local/python3/lib/python3.8/site-packages/web/application.py", line 466, in handle_class
    return tocall(*args)
  File "/root/data/chineseocr_lite_0311/chineseocr_lite-master/app.py", line 120, in POST
    return json.dumps({'res':res,'timeTake':round(timeTake,4)},ensure_ascii=False)
UnboundLocalError: local variable 'res' referenced before assignment

192.168.11.99:54227 - - [12/Mar/2020 17:43:52] "HTTP/1.1 POST /ocr" - 500 Internal Server Error

**Comment by Caesarthegreat** [comment]
下载了3.12号更新的版本后，这个报错神奇的消失了。。。
