### ISSUE TITLE
linux下找不到libOcrLiteNcnn.so无法打开共享对象文件：没有这样的文件或目录

### ISSUE THREAD

**Issue by xl111** [ouyanghuiyu/chineseocr_lite#344]
Caused by: java.lang.UnsatisfiedLinkError: /home/weblogic/user_projects/domains/test_domain/WebRoot/Linux-Lib-CPU/libOcrLiteNcnn.so: libmvec.so.1: cannot open shared object file: No such file or directory
	at java.lang.ClassLoader$NativeLibrary.load(Native Method) ~[?:1.7.0_80]
	at java.lang.ClassLoader.loadLibrary1(ClassLoader.java:1965) ~[?:1.7.0_80]
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1890) ~[?:1.7.0_80]
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1851) ~[?:1.7.0_80]
	at java.lang.Runtime.load0(Runtime.java:795) ~[?:1.7.0_80]
	at java.lang.System.load(System.java:1062) ~[?:1.7.0_80]
	at com.benjaminwan.ocrlibrary.OcrEngine.<init>(OcrEngine.kt:11) ~[debt-lgfv-h.jar:?]
	at com.lgfv.debt.ywgl.dataImportProcessing.action.DataImportProcessingAction.orcTest(DataImportProcessingAction.java:164) ~[debt-lgfv-h.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_80]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[?:1.7.0_80]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.7.0_80]
	at java.lang.reflect.Method.invoke(Method.java:606) ~[?:1.7.0_80]
	at ognl.OgnlRuntime.invokeMethod(OgnlRuntime.java:871) ~[ognl-3.0.19.jar:?]
	at ognl.OgnlRuntime.callAppropriateMethod(OgnlRuntime.java:1294) ~[ognl-3.0.19.jar:?]
	... 76 more

**Comment by chienkan** [comment]
```
$ ldd /home/weblogic/user_projects/domains/test_domain/WebRoot/Linux-Lib-CPU/libOcrLiteNcnn.s | grep not
```
看看输出
