### ISSUE TITLE
NotImplementedError 运行后出现如下报错,不知道是什么原因

### ISSUE THREAD

**Issue by luxiaolan6373** [ouyanghuiyu/chineseocr_lite#387]
运行后出现如下报错,不知道是什么原因

2021-11-17 20:10:41.0305976 [W:onnxruntime:, graph.cc:3391 onnxruntime::Graph::CleanUnusedInitializers] Removing initializer '88'. It is not used by any node and should be removed from the model.
2021-11-17 20:10:41.0306080 [W:onnxruntime:, graph.cc:3391 onnxruntime::Graph::CleanUnusedInitializers] Removing initializer '94'. It is not used by any node and should be removed from the model.
Traceback (most recent call last):
  File "E:/pythonProjects/chineseocr_lite-onnx/backend/main.py", line 43, in <module>
    server.start(1)
  File "D:\Users\y7000\anaconda3\envs\py38_32\lib\site-packages\tornado\tcpserver.py", line 222, in start
    self.add_sockets(sockets)
  File "D:\Users\y7000\anaconda3\envs\py38_32\lib\site-packages\tornado\tcpserver.py", line 157, in add_sockets
    self._handlers[sock.fileno()] = add_accept_handler(
  File "D:\Users\y7000\anaconda3\envs\py38_32\lib\site-packages\tornado\netutil.py", line 268, in add_accept_handler
    io_loop.add_handler(sock, accept_handler, IOLoop.READ)
  File "D:\Users\y7000\anaconda3\envs\py38_32\lib\site-packages\tornado\platform\asyncio.py", line 79, in add_handler
    self.asyncio_loop.add_reader(
  File "D:\Users\y7000\anaconda3\envs\py38_32\lib\asyncio\events.py", line 501, in add_reader
    raise NotImplementedError
NotImplementedError

Process finished with exit code 1

**Comment by luxiaolan6373** [comment]
我解决了,,是python版本问题,必须python3.6 和64位

**Comment by bill-work-acc** [comment]
FYI: https://github.com/tornadoweb/tornado/issues/2804

临时Workaround: https://github.com/tornadoweb/tornado/issues/2804#issuecomment-611628263
