### ISSUE TITLE
docker运行时报错

### ISSUE THREAD

**Issue by jack80342** [ouyanghuiyu/chineseocr_lite#398]
ERROR:tornado.application:Uncaught exception POST /api/tr-run/ (172.17.0.1)
HTTPServerRequest(protocol='http', host='localhost:8089', method='POST', uri='/api/tr-run/', version='HTTP/1.1', remote_ip='172.17.0.1')
Traceback (most recent call last):
  File "/usr/local/lib64/python3.6/site-packages/tornado/web.py", line 1592, in _execute
    result = yield result
  File "/usr/local/lib64/python3.6/site-packages/tornado/gen.py", line 1133, in run
    value = future.result()
  File "/usr/local/lib64/python3.6/site-packages/tornado/gen.py", line 307, in wrapper
    result = func(*args, **kwargs)
  File "/usr/lib64/python3.6/types.py", line 248, in wrapped
    coro = func(*args, **kwargs)
  File "/data/project/backend/webInterface/tr_run.py", line 155, in post
    myfont = ImageFont.truetype("\u4eff\u5b8b_GB2312.ttf", size=size)
  File "/usr/local/lib64/python3.6/site-packages/PIL/ImageFont.py", line 655, in truetype
    return freetype(font)
  File "/usr/local/lib64/python3.6/site-packages/PIL/ImageFont.py", line 652, in freetype
    return FreeTypeFont(font, size, index, encoding, layout_engine)
  File "/usr/local/lib64/python3.6/site-packages/PIL/ImageFont.py", line 194, in __init__
    font, size, index, encoding, layout_engine=layout_engine
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-1: ordinal not in range(128)
ERROR:tornado.access:500 POST /api/tr-run/ (172.17.0.1) 3213.92ms

**Comment by fsyj123** [comment]
请问这个问题得到解决了吗？我也正使用docker运行，也是出现这个问题

**Comment by fsyj123** [comment]
> 请问这个问题得到解决了吗？我也正使用docker运行，也是出现这个问题

将中文字符集名称改为英文，并且修正了路径，得到解决
