### ISSUE TITLE
能否支持linux版本

### ISSUE THREAD

**Issue by haifding** [ouyanghuiyu/chineseocr_lite#419]
.net core3.1、NET6 程序会放到  CentOS7.9上面去运行。现在windows可以正常使用 , linux服务上报错

=======message=======The type initializer for 'Emgu.CV.CvInvoke' threw an exception.|   at Emgu.CV.CvInvoke.Imread(String filename, ImreadModes loadType)
   at OcrLiteLib.OcrLite.Detect(String img, Int32 padding, Int32 imgResize, Single boxScoreThresh, Single boxThresh, Single unClipRatio, Boolean doAngle, Boolean mostAngle)
   at NetModular.Module.Scrm.Web.Controllers.FansAccountController.ceshitupian() in D:\Program Files\Jenkins\.jenkins\workspace\Dev-FishScrm-API\src\Web\Controllers\FansAccountController.cs:line 177

**Comment by benjaminwan** [comment]
一般linux的bin或dll都需要本机编译。如果nuget上面没有提供对应的版本，那就没办法了。
