### ISSUE TITLE
Ubuntu 18.04 make error

### ISSUE THREAD

**Issue by GeekRicardo** [ouyanghuiyu/chineseocr_lite#54]
```shell
(base) ricardo @ azure:(~/chineseocr_lite/psenet/pse)
-> make
g++ -o pse.so -I include  -std=c++11 -O3 -I/usr/local/anaconda3/include/python3.7m -I/usr/local/anaconda3/include/python3.7m  -Wno-unused-result -Wsign-compare -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O3 -ffunction-sections -pipe  -fdebug-prefix-map=/tmp/build/80754af9/python_1565725737370/work=/usr/local/src/conda/python-3.7.4 -fdebug-prefix-map=/usr/local/anaconda3=/usr/local/src/conda-prefix -fuse-linker-plugin -ffat-lto-objects -flto-partition=none -flto -DNDEBUG -fwrapv -O3 -Wall -L/usr/local/anaconda3/lib/python3.7/config-3.7m-x86_64-linux-gnu -L/usr/local/anaconda3/lib -lpython3.7m -lcrypt -lpthread -ldl  -lutil -lrt -lm  pse.cpp --shared -fPIC
pse.cpp: In function ‘std::vector<std::vector<int> > pse::pse(pybind11::array_t<int, 1>, pybind11::array_t<unsigned char, 1>, int)’:
pse.cpp:32:29: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
         for (size_t i = 0; i<h; i++)
                            ~^~
pse.cpp:39:29: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
         for (size_t i = 0; i<h; i++)
                            ~^~
pse.cpp:42:32: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
             for(size_t j = 0; j<w; j++)
```
I use `python3.7` in `anaconda3`,what should I do now?

**Comment by GeekRicardo** [comment]
```bash
(base) ricardo @ azure:(~/chineseocr_lite)
-> python app.py 8080
make: Entering directory '/home/ricardo/chineseocr_lite/psenet/pse'
make: 'pse.so' is up to date.
make: Leaving directory '/home/ricardo/chineseocr_lite/psenet/pse'
device: cpu
load model
device: cpu
load model
device: cpu
load model
device: cpu
load model
Traceback (most recent call last):
  File "/usr/local/anaconda3/lib/python3.7/site-packages/web/utils.py", line 526, in take
    yield next(seq)
StopIteration

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "app.py", line 125, in <module>
    app = web.application(urls, globals())
  File "/usr/local/anaconda3/lib/python3.7/site-packages/web/application.py", line 62, in __init__
    self.init_mapping(mapping)
  File "/usr/local/anaconda3/lib/python3.7/site-packages/web/application.py", line 130, in init_mapping
    self.mapping = list(utils.group(mapping, 2))
  File "/usr/local/anaconda3/lib/python3.7/site-packages/web/utils.py", line 531, in group
    x = list(take(seq, size))
RuntimeError: generator raised StopIteration
```

**Comment by GeekRicardo** [comment]
emmmm, it's a bug in web.py/utils.py
Solution:[Python3.7运行web.py测试时出现RuntimeError: generator raised StopIteration异常](https://blog.csdn.net/qq_38591756/article/details/84971485)
Modify `/path/to/lib/python3.7/site-packages/web/utils.py`  row `524 take()`
```python
 524   def take(seq, n):
 525         for i in range(n):
 526              yield next(seq)
```
to
```python
524     def take(seq, n):
 525         for i in range(n):
 526             try:
 527                 yield next(seq)
 528             except StopIteration:
 529                 return
```

**Comment by xtccc** [comment]
https://github.com/ouyanghuiyu/chineseocr_lite/issues/22#issuecomment-597030790
有类似的结果
web.py 版本问题吧，我也是这样，升级web.py到最新（0.5）后就能编译了
