### ISSUE TITLE
转出来的onnx转到ncnn里面去，得到的maxindex全是-1

### ISSUE THREAD

**Issue by deep-practice** [ouyanghuiyu/chineseocr_lite#61]
转换代码：
            self.net.eval()
            output_onnx = 'crnn_lite_lstm_v2.onnx'
            input_names = ["input"]
            output_names = ["out"]
            inputs = torch.randn(1, 1, 32, 277)
            torch.onnx.export(net, inputs, output_onnx, export_params=True, verbose=False, input_names=input_names,keep_initializers_as_inputs=True,
                               output_names=output_names,opset_version=11)

模型文件我放在百度云上了，麻烦帮忙看看
链接：https://pan.baidu.com/s/1dZwUMjyHRXNjDtufUBKTTQ 
提取码：7rhm

**Comment by ouyanghuiyu** [comment]
https://zhuanlan.zhihu.com/p/113338890?utm_source=qq&utm_medium=social&utm_oi=645149500650557440 是使用这个教程的吗

**Comment by ouyanghuiyu** [comment]
> 转换代码：
> self.net.eval()
> output_onnx = 'crnn_lite_lstm_v2.onnx'
> input_names = ["input"]
> output_names = ["out"]
> inputs = torch.randn(1, 1, 32, 277)
> torch.onnx.export(net, inputs, output_onnx, export_params=True, verbose=False, input_names=input_names,keep_initializers_as_inputs=True,
> output_names=output_names,opset_version=11)
> 
> 模型文件我放在百度云上了，麻烦帮忙看看
> 链接：https://pan.baidu.com/s/1dZwUMjyHRXNjDtufUBKTTQ
> 提取码：7rhm

param 文件要修改的 上面链接写的很清楚 ， https://github.com/ouyanghuiyu/chineseocr_lite/tree/master/ncnn_project/models 这里已经有转化好的模型文件

**Comment by deep-practice** [comment]
对，我就是按照nihui大佬的教程来的，你指的param文件要修改是哪个地方，我看了我转出来的param结构上是对的上的。同时我也用onnxruntime验证了一下我的onnx是可以正常推理的。
主要是需要导出自己的crnn模型，所以得把整个过程跑通，233333

**Comment by ouyanghuiyu** [comment]
![image](https://user-images.githubusercontent.com/42023607/76921887-0f916e00-690a-11ea-87b3-6d33e3e585e8.png)
这里就是讲怎么修改的

**Comment by ouyanghuiyu** [comment]
0x4 手工微调模型和ncnn推理实现  
![image](https://user-images.githubusercontent.com/42023607/76921934-36e83b00-690a-11ea-83af-3fdf34a2c58d.png)
这里就是讲怎么修改的，还有你要用ncnn 的master最新的代码编译

**Comment by deep-practice** [comment]
我照着这个改了的，生成的param也是一样的结构。。。。。然而替换掉项目里面的param和bin，运行结果就全是-1

**Comment by ouyanghuiyu** [comment]
> 我照着这个改了的，生成的param也是一样的结构。。。。。然而替换掉项目里面的param和bin，运行结果就全是-1

模型结构一样的话 只替换bin就可以啦

**Comment by deep-practice** [comment]
按照你说的，我直接替换bin，运行是对的，但是我想知道我的param到底是怎么就错了。。。不然换个结构一样GG呀

**Comment by ouyanghuiyu** [comment]
> 按照你说的，我直接替换bin，运行是对的，但是我想知道我的param到底是怎么就错了。。。不然换个结构一样GG呀

应该是修改有细节没改对，你可以对比一下 两个param，nihui大佬也详细写了 https://zhuanlan.zhihu.com/p/93017149

**Comment by deep-practice** [comment]
可以了，我误解了什么叫手工修改，以为在代码里面改了就行，结果还需要在param里面稍微修改一下。。。

**Comment by cqray1990** [comment]
@deep-practice 
HI:
how did you convert to onnx? when i convert shufflenet_v2_x0_5 to onnx model it raise ValueError: only one element tensors can be converted to Python scalars

the code is as follows:
import  sys
#import  mxnet as mx
sys.path.insert(0,"..")
from crnn import LiteCrnn
from utils0nnx import  load_model
import  torch
from angle_class import shufflenet_v2_x0_5

from crnn.keys import alphabetChinese as alphabet
nh = 256
net   = shufflenet_v2_x0_5(num_classes=4, pretrained=False)

net = load_model(net, '../models/shufflenetv2_05.pth')
net.eval()

print('Finished loading model!')
print(net)
device = torch.device("cpu")
net = net.to(device)

##################export###############
output_onnx = './shufflenetv2_05.onnx'
print("==> Exporting model to ONNX format at '{}'".format(output_onnx))
input_names = ["input"]
# output_names = ["hm" , "wh"  , "reg"]
output_names = ["out" ]
inputs = torch.randn(1, 3, 48, 196).to(device)
torch_out = torch.onnx._export(net, inputs, output_onnx, export_params=True, verbose=False,
                               input_names=input_names, output_names=output_names)


import  os
os.system("python -m onnxsim {0} {0}".format(output_onnx))

**Comment by deep-practice** [comment]
@cqray1990 Do you modify the original code?I can export the onnx successfully.

**Comment by cqray1990** [comment]
@deep-practice i didn't modify the orginal code,it is so wired

**Comment by cqray1990** [comment]
@can you share your convert code? Thank you

**Comment by deep-practice** [comment]
I just clone the repo after you post the issue...

**Comment by deep-practice** [comment]
I think you should show more detailed error info.Besides pytorch version matters.

**Comment by cqray1990** [comment]
my torch version is 1.1 and what's your torch version?

**Comment by deep-practice** [comment]
1.2.0

**Comment by cqray1990** [comment]
==> Exporting model to ONNX format at './shufflenetv2_05.onnx'
Traceback (most recent call last):
  File "/home/lgx/下载/chineseocr_lite-master/onnx/convert_onnx.py", line 29, in <module>
    input_names=input_names, output_names=output_names)
  File "/home/lgx/.local/lib/python3.6/site-packages/torch/onnx/__init__.py", line 19, in _export
    result = utils._export(*args, **kwargs)
  File "/home/lgx/.local/lib/python3.6/site-packages/torch/onnx/utils.py", line 363, in _export
    _retain_param_name, do_constant_folding)
  File "/home/lgx/.local/lib/python3.6/site-packages/torch/onnx/utils.py", line 278, in _model_to_graph
    _disable_torch_constant_prop=_disable_torch_constant_prop)
  File "/home/lgx/.local/lib/python3.6/site-packages/torch/onnx/utils.py", line 188, in _optimize_graph
    graph = torch._C._jit_pass_onnx(graph, operator_export_type)
  File "/home/lgx/.local/lib/python3.6/site-packages/torch/onnx/__init__.py", line 50, in _run_symbolic_function
    return utils._run_symbolic_function(*args, **kwargs)
  File "/home/lgx/.local/lib/python3.6/site-packages/torch/onnx/utils.py", line 589, in _run_symbolic_function
    return fn(g, *inputs, **attrs)
  File "/home/lgx/.local/lib/python3.6/site-packages/torch/onnx/symbolic.py", line 412, in symbolic
    dim, keepdim = _get_const(dim, 'i', 'dim'), _get_const(keepdim, 'i', 'keepdim')
  File "/home/lgx/.local/lib/python3.6/site-packages/torch/onnx/symbolic.py", line 116, in _get_const
    return _parse_arg(value, desc)
  File "/home/lgx/.local/lib/python3.6/site-packages/torch/onnx/symbolic.py", line 75, in _parse_arg
    return int(tval)
ValueError: only one element tensors can be converted to Python scalars
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 63, in apport_excepthook
    from apport.fileutils import likely_packaged, get_recent_crashes
  File "/usr/lib/python3/dist-packages/apport/__init__.py", line 5, in <module>
    from apport.report import Report
  File "/usr/lib/python3/dist-packages/apport/report.py", line 30, in <module>
    import apport.fileutils
  File "/usr/lib/python3/dist-packages/apport/fileutils.py", line 23, in <module>
    from apport.packaging_impl import impl as packaging
  File "/usr/lib/python3/dist-packages/apport/packaging_impl.py", line 23, in <module>
    import apt
  File "/usr/lib/python3/dist-packages/apt/__init__.py", line 23, in <module>
    import apt_pkg
ModuleNotFoundError: No module named 'apt_pkg'

Original exception was:
Traceback (most recent call last):
  File "/home/lgx/下载/chineseocr_lite-master/onnx/convert_onnx.py", line 29, in <module>
    input_names=input_names, output_names=output_names)
  File "/home/lgx/.local/lib/python3.6/site-packages/torch/onnx/__init__.py", line 19, in _export
    result = utils._export(*args, **kwargs)
  File "/home/lgx/.local/lib/python3.6/site-packages/torch/onnx/utils.py", line 363, in _export
    _retain_param_name, do_constant_folding)
  File "/home/lgx/.local/lib/python3.6/site-packages/torch/onnx/utils.py", line 278, in _model_to_graph
    _disable_torch_constant_prop=_disable_torch_constant_prop)
  File "/home/lgx/.local/lib/python3.6/site-packages/torch/onnx/utils.py", line 188, in _optimize_graph
    graph = torch._C._jit_pass_onnx(graph, operator_export_type)
  File "/home/lgx/.local/lib/python3.6/site-packages/torch/onnx/__init__.py", line 50, in _run_symbolic_function
    return utils._run_symbolic_function(*args, **kwargs)
  File "/home/lgx/.local/lib/python3.6/site-packages/torch/onnx/utils.py", line 589, in _run_symbolic_function
    return fn(g, *inputs, **attrs)
  File "/home/lgx/.local/lib/python3.6/site-packages/torch/onnx/symbolic.py", line 412, in symbolic
    dim, keepdim = _get_const(dim, 'i', 'dim'), _get_const(keepdim, 'i', 'keepdim')
  File "/home/lgx/.local/lib/python3.6/site-packages/torch/onnx/symbolic.py", line 116, in _get_const
    return _parse_arg(value, desc)
  File "/home/lgx/.local/lib/python3.6/site-packages/torch/onnx/symbolic.py", line 75, in _parse_arg
    return int(tval)
ValueError: only one element tensors can be converted to Python scalars

**Comment by cqray1990** [comment]
i will try torch 1.2.0
