### ISSUE TITLE
mac环境启动app.py报错

### ISSUE THREAD

**Issue by laiyipeng** [ouyanghuiyu/chineseocr_lite#85]
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/web/utils.py", line 526, in take
    yield next(seq)
StopIteration

Traceback (most recent call last):
  File "app.py", line 118, in <module>
    app = web.application(urls, globals())
  File "/usr/local/lib/python3.7/site-packages/web/application.py", line 62, in __init__
    self.init_mapping(mapping)
  File "/usr/local/lib/python3.7/site-packages/web/application.py", line 130, in init_mapping
    self.mapping = list(utils.group(mapping, 2))
  File "/usr/local/lib/python3.7/site-packages/web/utils.py", line 531, in group
    x = list(take(seq, size))
RuntimeError: generator raised StopIteration
```

`torch==1.2.0`
`torchvision==0.4.0`
`pillow==6.1`
`python3.7.3`
环境是否有问题？

**Comment by laiyipeng** [comment]
edit title

**Comment by laiyipeng** [comment]
requirements中web.py改为0.40.0后正常运行

**Comment by BeHappyForMe** [comment]
请问是0.40.dev0还是0.40.0呀

**Comment by xugaoxiang** [comment]
pip install -U web.py
